Healthcheck: don't stop a subnode container if !job.chainsToStart.isEmpty() (but chain can't start due to bad config)
Error: DefaultSubnodeAdminClient - startBlockchain(100) -- can't start blockchain: INTERNAL: Database initialization failed